Repository True-Stay/true-stay-app, pull requests merged in 2020-12, with the labels that each got.

#28 Rikinp
  assets/images/apartments.jpeg
  assets/images/apartments1.jpeg
  assets/images/building1.jpeg
  assets/images/building2.jpeg
  assets/images/house1.jpeg
  assets/images/house2.jpeg
  assets/images/houses.jpeg
  assets/images/houses1.jpeg
  package-lock.json
  package.json
  src/components/ListView/index.tsx
  src/pages/ActivityFeed/index.tsx
  src/pages/DetailsPage/index.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/index.tsx
  src/routes/index.tsx
  src/utils/global/index.tsx
Labels: Defect, fixed, needs fix

#31 Adding filter for search page
  package-lock.json
  package.json
  src/pages/Search/index.tsx
  src/routes/index.tsx
Labels: enhancement, new feature

#33 Listing Details Scrren
  package-lock.json
  src/pages/DetailsPage/index.tsx
  src/pages/PasswordReset/index.tsx
  src/styles/global-styles.ts
Labels: enhancement

#36 Made Major Changes in all the Screens and Added new screens
  package-lock.json
  package.json
  src/components/Button/index.tsx
  src/components/Card/index.tsx
  src/components/Header/index.tsx
  src/components/ListCard/CardItemList.tsx
  src/components/ListCard/ListCard.tsx
  src/components/ListCard/index.tsx
  src/pages/ActivityFeed/ActivityFeedScreen.tsx
  src/pages/ActivityFeed/ContentTitle.tsx
  src/pages/ActivityFeed/Navigator.tsx
  src/pages/ActivityFeed/PageContent.tsx
  src/pages/ActivityFeed/index.tsx
  src/pages/DetailsPage/DescriptionCard.tsx
  src/pages/DetailsPage/DetailsPageScreen.tsx
  src/pages/DetailsPage/LandlordInfoCard.tsx
  src/pages/DetailsPage/UnitCard.tsx
  src/pages/DetailsPage/index.tsx
  src/pages/LandlordListings/index.tsx
  src/pages/Listing/ModifyListingScreen.tsx
  src/pages/Listing/PostListingScreen.tsx
  src/pages/LoginPage/index.tsx
  src/pages/Menu/index.tsx
  src/pages/Onboarding/index.tsx
  src/pages/Search/index.tsx
  src/pages/Signup/SignUpScreen.tsx
  src/routes/index.tsx
  src/styles/global-styles.ts
Labels: enhancement

#32 Adding landlord search screen
  package-lock.json
  package.json
  src/pages/LandlordSearch/index.tsx
  src/routes/index.tsx
Labels: new feature

#37 George branch
  src/pages/Onboarding/index.tsx
  src/routes/index.tsx
  src/styles/global-styles.ts
Labels: enhancement

#35 Teresa new
  src/pages/Profile/index.tsx
Labels: new feature

#39 Geroge branch
  debug.log
  package-lock.json
  src/components/ListCard/CardItemList.tsx
  src/pages/ActivityFeed/ActivityFeedScreen.tsx
  src/pages/DetailsPage/DetailsPageScreen.tsx
  src/pages/Menu/Footer.tsx
  src/pages/Menu/Header.tsx
  src/pages/Menu/index.tsx
  src/routes/index.tsx
  src/styles/global-styles.ts
Labels: Defect, documentation, enhancement

#40 fixed bugs in edit profile
  package-lock.json
  package.json
  src/components/Button/index.tsx
  src/components/Card/index.tsx
  src/components/Header/index.tsx
  src/pages/ActivityFeed/ActivityFeedScreen.tsx
  src/pages/ActivityFeed/ContentTitle.tsx
  src/pages/ActivityFeed/DataLoader.tsx
  src/pages/ActivityFeed/Navigator.tsx
  src/pages/ActivityFeed/PageContent.tsx
  src/pages/LandlordListings/index.tsx
  src/pages/Listing/Greetings.tsx
  src/pages/Listing/ImageComponent.tsx
  src/pages/Listing/ImageLoader.tsx
  src/pages/Listing/ModifyListingScreen.tsx
  src/pages/Listing/PostListingScreen.tsx
  src/pages/Listing/inputChangeHandler.tsx
  src/pages/Listing/networkRequest.tsx
  src/pages/LoginPage/index.tsx
  src/pages/Menu/Footer.tsx
  src/pages/Onboarding/index.tsx
  src/pages/PasswordReset/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Signup/SignUpScreen.tsx
  src/pages/UserProfile/index.tsx
  src/routes/index.tsx
  src/styles/global-styles.ts
  src/utils/Storage/index.ts
Labels: enhancement

#42 added tests
  package-lock.json
  package.json
  src/__tests__/__snapshots__/App-test.tsx.snap.android
  src/__tests__/__snapshots__/App-test.tsx.snap.ios
  src/__tests__/__snapshots__/App-test.tsx.snap.web
  src/__tests__/__snapshots__/Backgrouund-test.tsx.snap.android
  src/__tests__/__snapshots__/Backgrouund-test.tsx.snap.ios
  src/__tests__/__snapshots__/Backgrouund-test.tsx.snap.web
  src/__tests__/__snapshots__/background-test.tsx.snap.android
  src/__tests__/__snapshots__/background-test.tsx.snap.ios
  src/__tests__/__snapshots__/background-test.tsx.snap.web
  src/__tests__/api.js
  src/__tests__/background-test.tsx
  src/pages/ActivityFeed/ActivityFeedScreen.tsx
  src/pages/Login/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/Menu/index.tsx
Labels: TEST PASSED
